# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/Vivado/CPU/CPU.cache/wt [current_project]
set_property parent.project_path G:/Vivado/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/Vivado/CPU/CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  G:/Vivado/CPU/CPU.srcs/sources_1/new/ALU.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/ALUControl.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/Adder30.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/CarryLookAhead_4.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/Counter8.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/Decoder3_8.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/EXT.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/FixedComplementAdder32.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/FrequencyDivider.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/GU.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/IFU.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/MainControl.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/Minus.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/NPC.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/PC.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/PU.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/ParallelAdder4.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/PartialCarryLookAheadAdder_16.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/PartialCarryLookAheadAdder_32.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/RF.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/SUM.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/Select.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/SevenSegDecoder.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/SevenSegDisp.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/SignExt.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/dm_4k.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/im_4k.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/mips.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/mux2.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/mux_2.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/mux_5_2.v
  G:/Vivado/CPU/CPU.srcs/sources_1/new/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/Vivado/CPU/CPU.srcs/constrs_1/new/N4.xdc
set_property used_in_implementation false [get_files G:/Vivado/CPU/CPU.srcs/constrs_1/new/N4.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
